name: Release Extension to Sonatype

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write
  pull-requests: write
  
jobs:
  release-hibernate6:
    uses: liquibase/build-logic/.github/workflows/extension-release-published.yml@DAT-16025
    with:
      branch: ${{ github.ref }}
    secrets: inherit

  release-hibernate5:
    uses: liquibase/build-logic/.github/workflows/extension-release-published.yml@DAT-16025
    with:
      branch: 'refs/heads/hibernate5'
    secrets: inherit